version: '3'
services:
  minecraft-server:
    image: itzg/minecraft-server
    environment:
      - EULA=TRUE
      - VERSION=1.20.4
        #      - MEMORY=4G
      - INIT_MEMORY=1G
      - MAX_MEMORY=4G
      - TYPE=PURPUR
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - /var/mc-data/:/data
    restart: on-failure

